routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('bases-laravel/pages/home');
});

// Auth::routes();

Route::get('home', 'HomeController@index')->name('home');
Route::get('about', 'HomeController@about')->name('about');
Route::get('help', 'HomeController@help')->name('help');

//EVENTS
Route::resource('events', 'EventController');

//SHORT URL
Route::resource('urls', 'UrlController');

app/Event.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Event extends Model
{
    protected $fillable = ['title', 'body', 'city', 'price', 'start_at'];
    
   	protected $casts = [
   		'start_at' => 'datetime'
   	];


   	public function isFree()
   	{
   		return $this->price==0 ? true : false;
   	}

   	public function getRouteKeyName()
   	{
   		return 'slug';
   	}

      protected static function boot()
      {
         parent::boot();

         static::creating(function ($event)
         {
            $event->slug = \Str::slug($event->title);
         });
      }
}

app/Http/Controllers/EventController.php
<?php

namespace App\Http\Controllers;

use App\Event;
use Illuminate\Http\Request;
use App\Http\Requests\Events\CreateEvent;
use App\Utilities\EventHelpers;

class EventController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('bases-laravel.pages.events.events')->withEvents(Event::Paginate(2));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('bases-laravel/pages/events/create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateEvent $request)
    {   
        // $slug = \Str::slug($request->title);
        Event::create([
            'title' => $request->title,
            'body' => $request->body,
            'city' => $request->city,
            'price' => $request->price
        ]);
        
        // EventHelpers::flash('L\'evenement a ete creer avec succes !');
        \Flashy::message('L\'evenement a ete creer avec succes !');
        return redirect(route('events.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Event  $event
     * @return \Illuminate\Http\Response
     */
    public function show(Event $event)
    {
        return view('bases-laravel.pages.events.event')->withEvent($event);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Event  $event
     * @return \Illuminate\Http\Response
     */
    public function edit(Event $event)
    {
        return view('bases-laravel.pages.events.update')->withEvent($event);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Event  $event
     * @return \Illuminate\Http\Response
     */
    public function update(CreateEvent $request, Event $event)
    {

        $event->update($request->all());
        // EventHelpers::flash('L\'evenement a ete modifie avec succes !');
        \Flashy::message('L\'evenement a ete modifie avec succes !');
        return view('bases-laravel.pages.events.event')->withEvent($event);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Event  $event
     * @return \Illuminate\Http\Response
     */
    public function destroy(Event $event)
    {
        $event->delete();
        // EventHelpers::flash('L\'evenement a ete supprime avec succes !', 'danger');
        \Flashy::error('L\'evenement a ete suprime avec succes !');
        return redirect(route('events.index'));
    }
}

resources/views/bases-laravel/pages/events/_form.blade.php
<div class="form-group">
	<label for="title">Title: </label>
	<input type="text" class="form-control {{ $errors->has('title')?'is-invalid':'' }}" id="title" name="title" value="{{ old('title')??$event->title }}">
	{!! $errors->first('title', '<span class="invalid-feedback">:message</span>') !!}
</div>

<div class="form-group">
	<label for="body">Text content</label>
	<textarea name="body" id="body" cols="30" rows="6" class="form-control {{ $errors->has('body') ? 'is-invalid' : '' }}">
		{{ old('body') ?? $event->body }}
	</textarea>
	{!! $errors->first('body', '<span class="invalid-feedback">:message</span>') !!}
</div>

<div class="row">
	<div class="col-md-6">
		<div class="form-group">
	  	<label for="city">City</label>
	  	<input type="text" name="city" id="city" class="form-control {{ $errors->has('city') ? 'is-invalid' :''}}" value="{{ old('city') ?? $event->city }}">
	  	{!! $errors->first('city', '<span class="invalid-feedback">:message<span>') !!}
  	</div>
	</div>

	<div class="col-md-6">
		<div class="form-group">
	  	<label for="price">Price</label>
	  	<input type="text" value="{{ old('price') ?? $event->price }}" name="price" id="price" class="form-control {{ $errors->has('price') ? 'is-invalid' : '' }}">
	  	{!! $errors->first('price', '<span class="invalid-feedback">:message</span>') !!}
  	</div>
	</div>
</div>
<input type="submit" class="btn btn-primary btn-block" value="{{ $submitButtonText }}">

resources/views/bases-laravel/pages/events/create.blade.php
<?php $event = new App\Event(); ?>
@extends('bases-laravel/layouts/app',['title' => 'create-event'])

@section('content')
	<div class="row">
		<div class="col-md-8 mx-auto">
			<h1 class="text-center lead text-success">Creer un evenement</h1>
			<form action="{{ route('events.store') }}" method="POST">
				@csrf
		  	@include('bases-laravel/pages/events/_form', ['submitButtonText' => 'Creer un evenement'])
			</form>
		</div>
	</div>
@endsection

resources/views/bases-laravel/pages/events/event.blade.php
@extends('bases-laravel.layouts.app', ['title' => 'events'])

@section('content')
  <h1 class="lead">{{ $event->title }}</h1>
  <p class="text-justify">{{ $event->body }}</p>
  <a href="{{ route('events.edit', $event) }}" class="btn btn-sm btn-outline-secondary">EDITER</a>
  <a href="{{ route('events.destroy', $event) }}" class="btn btn-sm btn-outline-danger" data-method="DELETE" data-confirm="êtes vous sûr?">DELETE</a>
@endsection

resources/views/bases-laravel/pages/events/events.blade.php
@extends('bases-laravel.layouts.app', ['title' => 'events'])

@section('content')
  <div class="row">
  	<div class="col-md-8 mx-auto">
	  	<div class="mb-3">
	  		<span class="text-secondary mr-3">Events count: {{ $events->count() }}</span>
	  		<a href="{{ route('events.create') }}" class="btn btn-sm btn-outline-success">Creer un Evenement</a>
	  	</div>

	  	@if ($events->count() > 0 )
			<div class="row">
		    @foreach($events as $event)
					<div class="col-md-6">
						<article class="pb-5">
							<h2 class="lead text-info">{{ $event->title }}</h2>
							<p class="text-justify">{{ $event->body }}</p>
							date: {{ format_date($event->start_at) }} *** price: {!! format_price($event) !!} <br>
							<a href="{{ route('events.show',$event) }}" class="btn btn-sm btn-primary">Detail</a>
						</article>
					</div>
		    @endforeach
			</div>
		    {{-- {{ $events->links('vendor/pagination/simple-default') }} --}}
		    {{ $events->links() }}
	    @else
			<p class="text-secondary text-center">Aucun evenement</p>
	  	@endif
  	</div>
  </div>
@endsection

resources/views/bases-laravel/pages/events/update.blade.php
@extends('bases-laravel.layouts.app', ['title' => $event->title])

@section('content')
	<div class="col">
		<div class="col-md-8 mx-auto">
		  <h1 class="lead">Update event</h1>
		  <form action="{{ route('events.update', $event)}}" method="POST">
		  	@method('PUT')
		  	@csrf
		  	@include('bases-laravel/pages/events/_form', ['submitButtonText' => 'Mettre a jour l\'evenement'])
		  </form>
		</div>
	</div>
@endsection