routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('bases-laravel/pages/home');
});

// Auth::routes();

Route::get('home', 'HomeController@index')->name('home');
Route::get('about', 'HomeController@about')->name('about');
Route::get('help', 'HomeController@help')->name('help');

//EVENTS
Route::resource('events', 'EventController');

//SHORT URL
Route::resource('urls', 'UrlController');

resources/views/bases-laravel/pages/shorturl/index.blade.php
@extends('bases-laravel.layouts.app', ['title' => 'shorturl'])

@section('content')
	<div class="row">
		<div class="col-md-6 mx-auto p-3">
			<h1 class="text-center lead text-secondary">Amazing url shortner there !!!</h1>
			<div>
				<form action="{{ route('urls.store') }}" method="POST">
					@csrf
					<input type="text" name="url" class="form-control form-control-sm mb-2 border-secondary" placeholder="Enter your original url" value="{{ old('url') }}">
					{!! $errors->first('url', '<p class="errors">:message</p>') !!}
					<input type="submit" value="GET SHORT URL" class="btn btn-sm btn-primary btn-block">
				</form>
			</div>
		</div>
	</div>
@endsection

resources/views/bases-laravel/pages/shorturl/shortened.blade.php
@extends('bases-laravel.layouts.app', ['title' => 'shortened'])

@section('content')
	<div class="row">
		<div class="col-md-8 mx-auto text-center mt-5">
			<h2 class="lead text-secondary text-center">YOUR SHORT URL BELOW !</h2>
			<a href="{{ route('urls.show', $shortened) }}" target="_blank">
				{{ env('APP_URL')}}/urls/{{ $shortened }}
			</a>
		</div>
	</div>
@endsection